### ISSUE TITLE
Provide Tinkerbell artwork to the CNCF

### ISSUE THREAD

**Issue by vielmetti** [tinkerbell/artwork#5]
## Expected Behaviour

The onboarding document https://github.com/cncf/sandbox/issues/263 suggests that
artwork for the project needs to be put in the CNCF artwork repo, https://github.com/cncf/artwork .
It also calls for some additional artwork formats not currently in this repository.

## Current Behaviour

Artwork not yet in CNCF repo.

## Possible Solution

Produce new versions to the specifications at https://github.com/cncf/artwork and 
do an issue PR there to update

## Steps to Reproduce (for bugs)

1.  Review https://github.com/cncf/artwork/tree/master/projects/tinkerbell
2.
3.
4.

## Context

part of the CNCF Onboarding process.

**Comment by nshalman** [comment]
https://github.com/cncf/artwork/blob/master/examples/sandbox.md#tinkerbell-logos looks like this might be done?
@vielmetti can we close this out?

**Comment by vielmetti** [comment]
Yup, added in https://github.com/cncf/artwork/pull/200 . This is done.
